<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.24">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Xiaohan Xie">

<title>assignment04</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="assignment_files/libs/clipboard/clipboard.min.js"></script>
<script src="assignment_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="assignment_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="assignment_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="assignment_files/libs/quarto-html/popper.min.js"></script>
<script src="assignment_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="assignment_files/libs/quarto-html/anchor.min.js"></script>
<link href="assignment_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="assignment_files/libs/quarto-html/quarto-syntax-highlighting-dc55a5b9e770e841cd82e46aadbfb9b0.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="assignment_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="assignment_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="assignment_files/libs/bootstrap/bootstrap-d6a003b94517c951b2d65075d42fb01b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">assignment04</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Xiaohan Xie </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressPackageStartupMessages</span>({</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">library</span>(AnnotationHub)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">library</span>(ensembldb)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">library</span>(GenomicRanges)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">library</span>(epiwraps)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">library</span>(rtracklayer)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">library</span>(ggplot2)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>})</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'dbplyr' was built under R version 4.5.2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'ggplot2' was built under R version 4.5.2</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>ah <span class="ot">&lt;-</span> <span class="fu">AnnotationHub</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<section id="load-the-peaks-for-p300-h3k27ac-and-h3k27me3-in-mouse-embryonic-stem-cells-mesc-and-in-one-differentiated-tissue-heart" class="level1">
<h1>1. Load the peaks for p300, H3K27ac and H3K27me3 in mouse embryonic stem cells (mESC) and in one differentiated tissue (heart)</h1>
<p>For the peaks data in heart, chip-seq data from 2 months old was used.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># load the files</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>bed_files <span class="ot">&lt;-</span> <span class="fu">list.files</span>(<span class="at">pattern =</span> <span class="st">"</span><span class="sc">\\</span><span class="st">.bed$"</span>, <span class="at">full.names =</span> <span class="cn">TRUE</span>)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>bed_names <span class="ot">&lt;-</span> <span class="fu">gsub</span>(<span class="st">"</span><span class="sc">\\</span><span class="st">.bed$"</span>, <span class="st">""</span>, <span class="fu">basename</span>(bed_files))</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>peaks <span class="ot">&lt;-</span> <span class="fu">lapply</span>(bed_files, <span class="at">FUN=</span>rtracklayer<span class="sc">::</span>import, <span class="at">format=</span><span class="st">"narrowPeak"</span>)</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(peaks) <span class="ot">&lt;-</span> bed_names</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(peaks)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>               Length Class   Mode
heart_H3K27ac  63061  GRanges S4  
heart_H3K27me3 22276  GRanges S4  
heart_p300     36497  GRanges S4  
msc_H3K27ac    88569  GRanges S4  
msc_H3K27me3   96897  GRanges S4  
msc_p300       23178  GRanges S4  </code></pre>
</div>
</div>
<p>use the genome from last assignment:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>ensdb_mouse <span class="ot">&lt;-</span> ah[[<span class="st">"AH89211"</span>]]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>loading from cache</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>ensdb_mouse </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>EnsDb for Ensembl:
|Backend: SQLite
|Db type: EnsDb
|Type of Gene ID: Ensembl Gene ID
|Supporting package: ensembldb
|Db created by: ensembldb package from Bioconductor
|script_version: 0.3.6
|Creation time: Sun Dec 20 12:15:16 2020
|ensembl_version: 102
|ensembl_host: localhost
|Organism: Mus musculus
|taxonomy_id: 10090
|genome_build: GRCm38
|DBSCHEMAVERSION: 2.1
| No. of genes: 56305.
| No. of transcripts: 144778.
|Protein data available.</code></pre>
</div>
</div>
<p>get the TSS coordinates, using the definition of TSS in annotateRegions:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>transcripts_mouse <span class="ot">&lt;-</span> <span class="fu">transcripts</span>(ensdb_mouse)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>tss <span class="ot">&lt;-</span> <span class="fu">promoters</span>(transcripts_mouse, <span class="at">upstream =</span> <span class="dv">2500</span>, <span class="at">downstream =</span> <span class="dv">1000</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in valid.GenomicRanges.seqinfo(x, suggest.trim = TRUE): GRanges object contains 4 out-of-bound ranges located on sequences
  JH584293.1, JH584294.1, JH584295.1, and JH584296.1. Note that ranges located
  on a sequence whose length is unknown (NA) or on a circular sequence are not
  considered out-of-bound (use seqlengths() and isCircular() to get the lengths
  and circularity flags of the underlying sequences). You can use trim() to
  trim these ranges. See ?`trim,GenomicRanges-method` for more information.</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(tss)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>GRanges object with 6 ranges and 9 metadata columns:
                     seqnames          ranges strand |              tx_id
                        &lt;Rle&gt;       &lt;IRanges&gt;  &lt;Rle&gt; |        &lt;character&gt;
  ENSMUST00000193812        1 3070753-3074252      + | ENSMUST00000193812
  ENSMUST00000082908        1 3099516-3103015      + | ENSMUST00000082908
  ENSMUST00000162897        1 3215345-3218844      - | ENSMUST00000162897
  ENSMUST00000159265        1 3214633-3218132      - | ENSMUST00000159265
  ENSMUST00000070533        1 3670499-3673998      - | ENSMUST00000070533
  ENSMUST00000192857        1 3250257-3253756      + | ENSMUST00000192857
                               tx_biotype tx_cds_seq_start tx_cds_seq_end
                              &lt;character&gt;        &lt;integer&gt;      &lt;integer&gt;
  ENSMUST00000193812                  TEC             &lt;NA&gt;           &lt;NA&gt;
  ENSMUST00000082908                snRNA             &lt;NA&gt;           &lt;NA&gt;
  ENSMUST00000162897 processed_transcript             &lt;NA&gt;           &lt;NA&gt;
  ENSMUST00000159265 processed_transcript             &lt;NA&gt;           &lt;NA&gt;
  ENSMUST00000070533       protein_coding          3216022        3671348
  ENSMUST00000192857 processed_pseudogene             &lt;NA&gt;           &lt;NA&gt;
                                gene_id tx_support_level        tx_id_version
                            &lt;character&gt;        &lt;integer&gt;          &lt;character&gt;
  ENSMUST00000193812 ENSMUSG00000102693             &lt;NA&gt; ENSMUST00000193812.1
  ENSMUST00000082908 ENSMUSG00000064842             &lt;NA&gt; ENSMUST00000082908.1
  ENSMUST00000162897 ENSMUSG00000051951                1 ENSMUST00000162897.1
  ENSMUST00000159265 ENSMUSG00000051951                1 ENSMUST00000159265.1
  ENSMUST00000070533 ENSMUSG00000051951                1 ENSMUST00000070533.4
  ENSMUST00000192857 ENSMUSG00000102851             &lt;NA&gt; ENSMUST00000192857.1
                     gc_content            tx_name
                      &lt;numeric&gt;        &lt;character&gt;
  ENSMUST00000193812    34.2056 ENSMUST00000193812
  ENSMUST00000082908    36.3636 ENSMUST00000082908
  ENSMUST00000162897    39.4895 ENSMUST00000162897
  ENSMUST00000159265    38.2068 ENSMUST00000159265
  ENSMUST00000070533    50.1376 ENSMUST00000070533
  ENSMUST00000192857    39.7917 ENSMUST00000192857
  -------
  seqinfo: 118 sequences (1 circular) from GRCm38 genome</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">seqlevelsStyle</span>(tss) <span class="ot">&lt;-</span> <span class="st">"UCSC"</span> <span class="co"># need to translate it to encode style</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in (function (seqlevels, genome, new_style) : cannot switch some
GRCm38's seqlevels from NCBI to UCSC style</code></pre>
</div>
</div>
</section>
<section id="compare-the-signals-across-the-two-tissues" class="level1">
<h1>2. Compare the signals across the two tissues</h1>
<section id="proportion-of-tss-that-overlap-h3k27ac-h3k27me3-and-the-combination-of-both-in-each-tissue" class="level2">
<h2 class="anchored" data-anchor-id="proportion-of-tss-that-overlap-h3k27ac-h3k27me3-and-the-combination-of-both-in-each-tissue">2.1 Proportion of TSS that overlap H3K27ac, H3K27me3, and the combination of both, in each tissue?</h2>
<p>Using type=“any” when counting the overlaps:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>targets <span class="ot">&lt;-</span> <span class="fu">list</span>(</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">msc_me3   =</span> peaks<span class="sc">$</span>msc_H3K27me3,</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">msc_ac    =</span> peaks<span class="sc">$</span>msc_H3K27ac,</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">heart_me3 =</span> peaks<span class="sc">$</span>heart_H3K27me3,</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">heart_ac  =</span> peaks<span class="sc">$</span>heart_H3K27ac</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a><span class="fu">sapply</span>(targets, <span class="at">FUN=</span><span class="cf">function</span>(x) <span class="fu">sum</span>(<span class="fu">overlapsAny</span>(tss, x, <span class="at">type =</span> <span class="st">"any"</span>))<span class="sc">/</span><span class="fu">length</span>(tss))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in .merge_two_Seqinfo_objects(x, y): Each of the 2 combined objects has sequence levels not in the other:
  - in 'x': CHR_CAST_EI_MMCHR11_CTG4, CHR_CAST_EI_MMCHR11_CTG5, CHR_MG104_PATCH, CHR_MG117_PATCH, CHR_MG132_PATCH, CHR_MG153_PATCH, CHR_MG171_PATCH, CHR_MG184_PATCH, CHR_MG190_MG3751_PATCH, CHR_MG191_PATCH, CHR_MG209_PATCH, CHR_MG3172_PATCH, CHR_MG3231_PATCH, CHR_MG3251_PATCH, CHR_MG3490_PATCH, CHR_MG3496_PATCH, CHR_MG3530_PATCH, CHR_MG3561_PATCH, CHR_MG3562_PATCH, CHR_MG3609_PATCH, CHR_MG3618_PATCH, CHR_MG3627_PATCH, CHR_MG3648_PATCH, CHR_MG3656_PATCH, CHR_MG3683_PATCH, CHR_MG3686_PATCH, CHR_MG3699_PATCH, CHR_MG3700_PATCH, CHR_MG3712_PATCH, CHR_MG3714_PATCH, CHR_MG3829_PATCH, CHR_MG3833_MG4220_PATCH, CHR_MG3835_PATCH, CHR_MG3836_PATCH, CHR_MG3999_PATCH, CHR_MG4136_PATCH, CHR_MG4138_PATCH, CHR_MG4151_PATCH, CHR_MG4162_PATCH, CHR_MG4180_PATCH, CHR_MG4198_PATCH, CHR_MG4200_PATCH, CHR_MG4209_PATCH, CHR_MG4211_PATCH, CHR_MG4212_PATCH, CHR_MG4213_PATCH, CHR_MG4214_PATCH, CHR_MG4222_MG3908_PATCH, CHR_MG4243_PATCH, CHR_MG4248_PATCH, CHR_MG4249_PATCH, CHR_MG4254_PATCH, CHR_MG4255_PATCH, CHR_MG4259_PATCH, CHR_MG4261_PATCH, CHR_MG4264_PATCH, CHR_MG4265_PATCH, CHR_MG4266_PATCH, CHR_MG4281_PATCH, CHR_MG4288_PATCH, CHR_MG4308_PATCH, CHR_MG4310_MG4311_PATCH, CHR_MG51_PATCH, CHR_MG65_PATCH, CHR_MG74_PATCH, CHR_MG89_PATCH, CHR_MMCHR1_CHORI29_IDD5_1, CHR_PWK_PHJ_MMCHR11_CTG1, CHR_PWK_PHJ_MMCHR11_CTG2, CHR_PWK_PHJ_MMCHR11_CTG3, CHR_WSB_EIJ_MMCHR11_CTG1, CHR_WSB_EIJ_MMCHR11_CTG2, CHR_WSB_EIJ_MMCHR11_CTG3, GL456210.1, GL456211.1, GL456212.1, GL456216.1, GL456219.1, GL456221.1, GL456233.1, GL456239.1, GL456350.1, GL456354.1, GL456372.1, GL456381.1, GL456385.1, JH584292.1, JH584293.1, JH584294.1, JH584295.1, JH584296.1, JH584297.1, JH584298.1, JH584299.1, JH584303.1, JH584304.1, chrM
  - in 'y': chrUn_GL456392, chrUn_JH584304, chrUn_GL456239, chrUn_GL456389, chrUn_GL456396, chrUn_GL456393, chr4_GL456216_random, chrUn_GL456383, chrUn_GL456390, chrUn_GL456370, chr4_JH584292_random, chrUn_GL456366, chrX_GL456233_random
  Make sure to always combine/compare objects based on the same reference
  genome (use suppressWarnings() to suppress this warning).</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in .merge_two_Seqinfo_objects(x, y): Each of the 2 combined objects has sequence levels not in the other:
  - in 'x': CHR_CAST_EI_MMCHR11_CTG4, CHR_CAST_EI_MMCHR11_CTG5, CHR_MG104_PATCH, CHR_MG117_PATCH, CHR_MG132_PATCH, CHR_MG153_PATCH, CHR_MG171_PATCH, CHR_MG184_PATCH, CHR_MG190_MG3751_PATCH, CHR_MG191_PATCH, CHR_MG209_PATCH, CHR_MG3172_PATCH, CHR_MG3231_PATCH, CHR_MG3251_PATCH, CHR_MG3490_PATCH, CHR_MG3496_PATCH, CHR_MG3530_PATCH, CHR_MG3561_PATCH, CHR_MG3562_PATCH, CHR_MG3609_PATCH, CHR_MG3618_PATCH, CHR_MG3627_PATCH, CHR_MG3648_PATCH, CHR_MG3656_PATCH, CHR_MG3683_PATCH, CHR_MG3686_PATCH, CHR_MG3699_PATCH, CHR_MG3700_PATCH, CHR_MG3712_PATCH, CHR_MG3714_PATCH, CHR_MG3829_PATCH, CHR_MG3833_MG4220_PATCH, CHR_MG3835_PATCH, CHR_MG3836_PATCH, CHR_MG3999_PATCH, CHR_MG4136_PATCH, CHR_MG4138_PATCH, CHR_MG4151_PATCH, CHR_MG4162_PATCH, CHR_MG4180_PATCH, CHR_MG4198_PATCH, CHR_MG4200_PATCH, CHR_MG4209_PATCH, CHR_MG4211_PATCH, CHR_MG4212_PATCH, CHR_MG4213_PATCH, CHR_MG4214_PATCH, CHR_MG4222_MG3908_PATCH, CHR_MG4243_PATCH, CHR_MG4248_PATCH, CHR_MG4249_PATCH, CHR_MG4254_PATCH, CHR_MG4255_PATCH, CHR_MG4259_PATCH, CHR_MG4261_PATCH, CHR_MG4264_PATCH, CHR_MG4265_PATCH, CHR_MG4266_PATCH, CHR_MG4281_PATCH, CHR_MG4288_PATCH, CHR_MG4308_PATCH, CHR_MG4310_MG4311_PATCH, CHR_MG51_PATCH, CHR_MG65_PATCH, CHR_MG74_PATCH, CHR_MG89_PATCH, CHR_MMCHR1_CHORI29_IDD5_1, CHR_PWK_PHJ_MMCHR11_CTG1, CHR_PWK_PHJ_MMCHR11_CTG2, CHR_PWK_PHJ_MMCHR11_CTG3, CHR_WSB_EIJ_MMCHR11_CTG1, CHR_WSB_EIJ_MMCHR11_CTG2, CHR_WSB_EIJ_MMCHR11_CTG3, GL456210.1, GL456211.1, GL456212.1, GL456216.1, GL456219.1, GL456221.1, GL456233.1, GL456239.1, GL456350.1, GL456354.1, GL456372.1, GL456381.1, GL456385.1, JH584292.1, JH584293.1, JH584294.1, JH584295.1, JH584296.1, JH584297.1, JH584298.1, JH584299.1, JH584303.1, JH584304.1, chrM
  - in 'y': chrUn_JH584304, chr4_GL456216_random, chrUn_GL456378, chrUn_GL456366, chrUn_GL456370, chrUn_GL456392, chrUn_GL456368, chrUn_GL456389, chrUn_GL456359
  Make sure to always combine/compare objects based on the same reference
  genome (use suppressWarnings() to suppress this warning).</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in .merge_two_Seqinfo_objects(x, y): Each of the 2 combined objects has sequence levels not in the other:
  - in 'x': CHR_CAST_EI_MMCHR11_CTG4, CHR_CAST_EI_MMCHR11_CTG5, CHR_MG104_PATCH, CHR_MG117_PATCH, CHR_MG132_PATCH, CHR_MG153_PATCH, CHR_MG171_PATCH, CHR_MG184_PATCH, CHR_MG190_MG3751_PATCH, CHR_MG191_PATCH, CHR_MG209_PATCH, CHR_MG3172_PATCH, CHR_MG3231_PATCH, CHR_MG3251_PATCH, CHR_MG3490_PATCH, CHR_MG3496_PATCH, CHR_MG3530_PATCH, CHR_MG3561_PATCH, CHR_MG3562_PATCH, CHR_MG3609_PATCH, CHR_MG3618_PATCH, CHR_MG3627_PATCH, CHR_MG3648_PATCH, CHR_MG3656_PATCH, CHR_MG3683_PATCH, CHR_MG3686_PATCH, CHR_MG3699_PATCH, CHR_MG3700_PATCH, CHR_MG3712_PATCH, CHR_MG3714_PATCH, CHR_MG3829_PATCH, CHR_MG3833_MG4220_PATCH, CHR_MG3835_PATCH, CHR_MG3836_PATCH, CHR_MG3999_PATCH, CHR_MG4136_PATCH, CHR_MG4138_PATCH, CHR_MG4151_PATCH, CHR_MG4162_PATCH, CHR_MG4180_PATCH, CHR_MG4198_PATCH, CHR_MG4200_PATCH, CHR_MG4209_PATCH, CHR_MG4211_PATCH, CHR_MG4212_PATCH, CHR_MG4213_PATCH, CHR_MG4214_PATCH, CHR_MG4222_MG3908_PATCH, CHR_MG4243_PATCH, CHR_MG4248_PATCH, CHR_MG4249_PATCH, CHR_MG4254_PATCH, CHR_MG4255_PATCH, CHR_MG4259_PATCH, CHR_MG4261_PATCH, CHR_MG4264_PATCH, CHR_MG4265_PATCH, CHR_MG4266_PATCH, CHR_MG4281_PATCH, CHR_MG4288_PATCH, CHR_MG4308_PATCH, CHR_MG4310_MG4311_PATCH, CHR_MG51_PATCH, CHR_MG65_PATCH, CHR_MG74_PATCH, CHR_MG89_PATCH, CHR_MMCHR1_CHORI29_IDD5_1, CHR_PWK_PHJ_MMCHR11_CTG1, CHR_PWK_PHJ_MMCHR11_CTG2, CHR_PWK_PHJ_MMCHR11_CTG3, CHR_WSB_EIJ_MMCHR11_CTG1, CHR_WSB_EIJ_MMCHR11_CTG2, CHR_WSB_EIJ_MMCHR11_CTG3, GL456210.1, GL456211.1, GL456212.1, GL456216.1, GL456219.1, GL456221.1, GL456233.1, GL456239.1, GL456350.1, GL456354.1, GL456372.1, GL456381.1, GL456385.1, JH584292.1, JH584293.1, JH584294.1, JH584295.1, JH584296.1, JH584297.1, JH584298.1, JH584299.1, JH584303.1, JH584304.1, chrM, chrY
  - in 'y': chr4_JH584292_random, chrUn_JH584304, chrUn_GL456239
  Make sure to always combine/compare objects based on the same reference
  genome (use suppressWarnings() to suppress this warning).</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>   msc_me3     msc_ac  heart_me3   heart_ac 
0.13968973 0.31757587 0.07320864 0.42874608 </code></pre>
</div>
</div>
<p>H3K27ac: associated with active/poised TSS. Proportion of TSS overlapping with H3K27ac peaks is much larger in heart (42.9%) than in mESC (31.8%), as heart is a differentiated organ that has more transcription activities than a stem cell. H3K27me3: associated with repressed gene expression, and has likewise less overlapping with TSS in heart than in stem cell.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>msc_both <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="fu">overlapsAny</span>(tss, peaks<span class="sc">$</span>msc_H3K27ac) <span class="sc">&amp;</span> </span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>                <span class="fu">overlapsAny</span>(tss, peaks<span class="sc">$</span>msc_H3K27me3)) <span class="sc">/</span> <span class="fu">length</span>(tss)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in .merge_two_Seqinfo_objects(x, y): Each of the 2 combined objects has sequence levels not in the other:
  - in 'x': CHR_CAST_EI_MMCHR11_CTG4, CHR_CAST_EI_MMCHR11_CTG5, CHR_MG104_PATCH, CHR_MG117_PATCH, CHR_MG132_PATCH, CHR_MG153_PATCH, CHR_MG171_PATCH, CHR_MG184_PATCH, CHR_MG190_MG3751_PATCH, CHR_MG191_PATCH, CHR_MG209_PATCH, CHR_MG3172_PATCH, CHR_MG3231_PATCH, CHR_MG3251_PATCH, CHR_MG3490_PATCH, CHR_MG3496_PATCH, CHR_MG3530_PATCH, CHR_MG3561_PATCH, CHR_MG3562_PATCH, CHR_MG3609_PATCH, CHR_MG3618_PATCH, CHR_MG3627_PATCH, CHR_MG3648_PATCH, CHR_MG3656_PATCH, CHR_MG3683_PATCH, CHR_MG3686_PATCH, CHR_MG3699_PATCH, CHR_MG3700_PATCH, CHR_MG3712_PATCH, CHR_MG3714_PATCH, CHR_MG3829_PATCH, CHR_MG3833_MG4220_PATCH, CHR_MG3835_PATCH, CHR_MG3836_PATCH, CHR_MG3999_PATCH, CHR_MG4136_PATCH, CHR_MG4138_PATCH, CHR_MG4151_PATCH, CHR_MG4162_PATCH, CHR_MG4180_PATCH, CHR_MG4198_PATCH, CHR_MG4200_PATCH, CHR_MG4209_PATCH, CHR_MG4211_PATCH, CHR_MG4212_PATCH, CHR_MG4213_PATCH, CHR_MG4214_PATCH, CHR_MG4222_MG3908_PATCH, CHR_MG4243_PATCH, CHR_MG4248_PATCH, CHR_MG4249_PATCH, CHR_MG4254_PATCH, CHR_MG4255_PATCH, CHR_MG4259_PATCH, CHR_MG4261_PATCH, CHR_MG4264_PATCH, CHR_MG4265_PATCH, CHR_MG4266_PATCH, CHR_MG4281_PATCH, CHR_MG4288_PATCH, CHR_MG4308_PATCH, CHR_MG4310_MG4311_PATCH, CHR_MG51_PATCH, CHR_MG65_PATCH, CHR_MG74_PATCH, CHR_MG89_PATCH, CHR_MMCHR1_CHORI29_IDD5_1, CHR_PWK_PHJ_MMCHR11_CTG1, CHR_PWK_PHJ_MMCHR11_CTG2, CHR_PWK_PHJ_MMCHR11_CTG3, CHR_WSB_EIJ_MMCHR11_CTG1, CHR_WSB_EIJ_MMCHR11_CTG2, CHR_WSB_EIJ_MMCHR11_CTG3, GL456210.1, GL456211.1, GL456212.1, GL456216.1, GL456219.1, GL456221.1, GL456233.1, GL456239.1, GL456350.1, GL456354.1, GL456372.1, GL456381.1, GL456385.1, JH584292.1, JH584293.1, JH584294.1, JH584295.1, JH584296.1, JH584297.1, JH584298.1, JH584299.1, JH584303.1, JH584304.1, chrM
  - in 'y': chrUn_JH584304, chr4_GL456216_random, chrUn_GL456378, chrUn_GL456366, chrUn_GL456370, chrUn_GL456392, chrUn_GL456368, chrUn_GL456389, chrUn_GL456359
  Make sure to always combine/compare objects based on the same reference
  genome (use suppressWarnings() to suppress this warning).</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in .merge_two_Seqinfo_objects(x, y): Each of the 2 combined objects has sequence levels not in the other:
  - in 'x': CHR_CAST_EI_MMCHR11_CTG4, CHR_CAST_EI_MMCHR11_CTG5, CHR_MG104_PATCH, CHR_MG117_PATCH, CHR_MG132_PATCH, CHR_MG153_PATCH, CHR_MG171_PATCH, CHR_MG184_PATCH, CHR_MG190_MG3751_PATCH, CHR_MG191_PATCH, CHR_MG209_PATCH, CHR_MG3172_PATCH, CHR_MG3231_PATCH, CHR_MG3251_PATCH, CHR_MG3490_PATCH, CHR_MG3496_PATCH, CHR_MG3530_PATCH, CHR_MG3561_PATCH, CHR_MG3562_PATCH, CHR_MG3609_PATCH, CHR_MG3618_PATCH, CHR_MG3627_PATCH, CHR_MG3648_PATCH, CHR_MG3656_PATCH, CHR_MG3683_PATCH, CHR_MG3686_PATCH, CHR_MG3699_PATCH, CHR_MG3700_PATCH, CHR_MG3712_PATCH, CHR_MG3714_PATCH, CHR_MG3829_PATCH, CHR_MG3833_MG4220_PATCH, CHR_MG3835_PATCH, CHR_MG3836_PATCH, CHR_MG3999_PATCH, CHR_MG4136_PATCH, CHR_MG4138_PATCH, CHR_MG4151_PATCH, CHR_MG4162_PATCH, CHR_MG4180_PATCH, CHR_MG4198_PATCH, CHR_MG4200_PATCH, CHR_MG4209_PATCH, CHR_MG4211_PATCH, CHR_MG4212_PATCH, CHR_MG4213_PATCH, CHR_MG4214_PATCH, CHR_MG4222_MG3908_PATCH, CHR_MG4243_PATCH, CHR_MG4248_PATCH, CHR_MG4249_PATCH, CHR_MG4254_PATCH, CHR_MG4255_PATCH, CHR_MG4259_PATCH, CHR_MG4261_PATCH, CHR_MG4264_PATCH, CHR_MG4265_PATCH, CHR_MG4266_PATCH, CHR_MG4281_PATCH, CHR_MG4288_PATCH, CHR_MG4308_PATCH, CHR_MG4310_MG4311_PATCH, CHR_MG51_PATCH, CHR_MG65_PATCH, CHR_MG74_PATCH, CHR_MG89_PATCH, CHR_MMCHR1_CHORI29_IDD5_1, CHR_PWK_PHJ_MMCHR11_CTG1, CHR_PWK_PHJ_MMCHR11_CTG2, CHR_PWK_PHJ_MMCHR11_CTG3, CHR_WSB_EIJ_MMCHR11_CTG1, CHR_WSB_EIJ_MMCHR11_CTG2, CHR_WSB_EIJ_MMCHR11_CTG3, GL456210.1, GL456211.1, GL456212.1, GL456216.1, GL456219.1, GL456221.1, GL456233.1, GL456239.1, GL456350.1, GL456354.1, GL456372.1, GL456381.1, GL456385.1, JH584292.1, JH584293.1, JH584294.1, JH584295.1, JH584296.1, JH584297.1, JH584298.1, JH584299.1, JH584303.1, JH584304.1, chrM
  - in 'y': chrUn_GL456392, chrUn_JH584304, chrUn_GL456239, chrUn_GL456389, chrUn_GL456396, chrUn_GL456393, chr4_GL456216_random, chrUn_GL456383, chrUn_GL456390, chrUn_GL456370, chr4_JH584292_random, chrUn_GL456366, chrX_GL456233_random
  Make sure to always combine/compare objects based on the same reference
  genome (use suppressWarnings() to suppress this warning).</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>heart_both <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="fu">overlapsAny</span>(tss, peaks<span class="sc">$</span>heart_H3K27ac) <span class="sc">&amp;</span> </span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>                  <span class="fu">overlapsAny</span>(tss, peaks<span class="sc">$</span>heart_H3K27me3)) <span class="sc">/</span> <span class="fu">length</span>(tss)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in .merge_two_Seqinfo_objects(x, y): Each of the 2 combined objects has sequence levels not in the other:
  - in 'x': CHR_CAST_EI_MMCHR11_CTG4, CHR_CAST_EI_MMCHR11_CTG5, CHR_MG104_PATCH, CHR_MG117_PATCH, CHR_MG132_PATCH, CHR_MG153_PATCH, CHR_MG171_PATCH, CHR_MG184_PATCH, CHR_MG190_MG3751_PATCH, CHR_MG191_PATCH, CHR_MG209_PATCH, CHR_MG3172_PATCH, CHR_MG3231_PATCH, CHR_MG3251_PATCH, CHR_MG3490_PATCH, CHR_MG3496_PATCH, CHR_MG3530_PATCH, CHR_MG3561_PATCH, CHR_MG3562_PATCH, CHR_MG3609_PATCH, CHR_MG3618_PATCH, CHR_MG3627_PATCH, CHR_MG3648_PATCH, CHR_MG3656_PATCH, CHR_MG3683_PATCH, CHR_MG3686_PATCH, CHR_MG3699_PATCH, CHR_MG3700_PATCH, CHR_MG3712_PATCH, CHR_MG3714_PATCH, CHR_MG3829_PATCH, CHR_MG3833_MG4220_PATCH, CHR_MG3835_PATCH, CHR_MG3836_PATCH, CHR_MG3999_PATCH, CHR_MG4136_PATCH, CHR_MG4138_PATCH, CHR_MG4151_PATCH, CHR_MG4162_PATCH, CHR_MG4180_PATCH, CHR_MG4198_PATCH, CHR_MG4200_PATCH, CHR_MG4209_PATCH, CHR_MG4211_PATCH, CHR_MG4212_PATCH, CHR_MG4213_PATCH, CHR_MG4214_PATCH, CHR_MG4222_MG3908_PATCH, CHR_MG4243_PATCH, CHR_MG4248_PATCH, CHR_MG4249_PATCH, CHR_MG4254_PATCH, CHR_MG4255_PATCH, CHR_MG4259_PATCH, CHR_MG4261_PATCH, CHR_MG4264_PATCH, CHR_MG4265_PATCH, CHR_MG4266_PATCH, CHR_MG4281_PATCH, CHR_MG4288_PATCH, CHR_MG4308_PATCH, CHR_MG4310_MG4311_PATCH, CHR_MG51_PATCH, CHR_MG65_PATCH, CHR_MG74_PATCH, CHR_MG89_PATCH, CHR_MMCHR1_CHORI29_IDD5_1, CHR_PWK_PHJ_MMCHR11_CTG1, CHR_PWK_PHJ_MMCHR11_CTG2, CHR_PWK_PHJ_MMCHR11_CTG3, CHR_WSB_EIJ_MMCHR11_CTG1, CHR_WSB_EIJ_MMCHR11_CTG2, CHR_WSB_EIJ_MMCHR11_CTG3, GL456210.1, GL456211.1, GL456212.1, GL456216.1, GL456219.1, GL456221.1, GL456233.1, GL456239.1, GL456350.1, GL456354.1, GL456372.1, GL456381.1, GL456385.1, JH584292.1, JH584293.1, JH584294.1, JH584295.1, JH584296.1, JH584297.1, JH584298.1, JH584299.1, JH584303.1, JH584304.1, chrM, chrY
  - in 'y': chr4_JH584292_random, chrUn_JH584304, chrUn_GL456239
  Make sure to always combine/compare objects based on the same reference
  genome (use suppressWarnings() to suppress this warning).</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Proportion of TSS overlapping both in mESC:"</span>, msc_both, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Proportion of TSS overlapping both in mESC: 0.01600381 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Proportion of TSS overlapping both in heart:"</span>, heart_both, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Proportion of TSS overlapping both in heart: 0.01815193 </code></pre>
</div>
</div>
<p>The proportion of TSS that overlaps both peaks is very low, which is as expected, as H3K27ac and H3K27me3 are on the same lysine and indicate opposite effects.</p>
</section>
<section id="relationship-between-the-three-signals-in-both-tissues" class="level2">
<h2 class="anchored" data-anchor-id="relationship-between-the-three-signals-in-both-tissues">2.2 Relationship between the three signals in both tissues</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>msc_peaks <span class="ot">&lt;-</span> <span class="fu">list</span>(</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">H3K27ac =</span> peaks<span class="sc">$</span>msc_H3K27ac,</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">H3K27me3 =</span> peaks<span class="sc">$</span>msc_H3K27me3,</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">p300 =</span> peaks<span class="sc">$</span>msc_p300</span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>heart_peaks <span class="ot">&lt;-</span> <span class="fu">list</span>(</span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">H3K27ac =</span> peaks<span class="sc">$</span>heart_H3K27ac,</span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">H3K27me3 =</span> peaks<span class="sc">$</span>heart_H3K27me3,</span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">p300 =</span> peaks<span class="sc">$</span>heart_p300</span>
<span id="cb31-11"><a href="#cb31-11" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb31-12"><a href="#cb31-12" aria-hidden="true" tabindex="-1"></a><span class="fu">regionOverlaps</span>(msc_peaks,<span class="at">main =</span> <span class="st">"Signal Overlaps in mESC"</span>) </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="assignment_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">regionOverlaps</span>(heart_peaks, <span class="at">main =</span> <span class="st">"Signal Overlaps in Heart"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="assignment_files/figure-html/unnamed-chunk-7-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Since the function of p300 is mainly to add acetyl groups to histone proteins, it could be seen from the plot that p300 and H3K27ac have very high overlaps, in both tissues. Again, as H3K27me3 and H3K27ac are signals on the same lysine and are indicators of contradictory effects, they are physically exclusive and do not show much overlaps. This could also be seen in both tissues.</p>
</section>
<section id="relationship-between-regulatory-elements-active-in-mesc-and-in-the-differentiated-tissue" class="level2">
<h2 class="anchored" data-anchor-id="relationship-between-regulatory-elements-active-in-mesc-and-in-the-differentiated-tissue">2.3 Relationship between regulatory elements active in mESC and in the differentiated tissue?</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>ac_both <span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="at">ac_msc =</span> peaks<span class="sc">$</span>msc_H3K27ac, <span class="at">ac_heart =</span> peaks<span class="sc">$</span>heart_H3K27ac)</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>me3_both <span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="at">me3_msc =</span> peaks<span class="sc">$</span>msc_H3K27me3, <span class="at">me3_heart =</span> peaks<span class="sc">$</span>heart_H3K27me3)</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>p300_both <span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="at">p300_msc =</span> peaks<span class="sc">$</span>msc_p300, <span class="at">p300_heart =</span> peaks<span class="sc">$</span>heart_p300)</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>areas <span class="ot">&lt;-</span> <span class="fu">list</span>(ac_both, me3_both, p300_both)</span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>ov_ac <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="fu">overlapsAny</span>(peaks<span class="sc">$</span>msc_H3K27ac, peaks<span class="sc">$</span>heart_H3K27ac, <span class="at">type =</span> <span class="st">"any"</span>))<span class="sc">/</span><span class="fu">length</span>(peaks<span class="sc">$</span>msc_H3K27ac)</span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Proportion of overlapping peaks between H3K27ac in mESC and heart:"</span>, ov_ac, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Proportion of overlapping peaks between H3K27ac in mESC and heart: 0.2693606 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>ov_me3 <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="fu">overlapsAny</span>(peaks<span class="sc">$</span>msc_H3K27me3, peaks<span class="sc">$</span>heart_H3K27me3, <span class="at">type =</span> <span class="st">"any"</span>))<span class="sc">/</span><span class="fu">length</span>(peaks<span class="sc">$</span>msc_H3K27me3)</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Proportion of overlapping peaks between H3K27me3 in mESC and heart:"</span>, ov_me3, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Proportion of overlapping peaks between H3K27me3 in mESC and heart: 0.08132347 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>ov_p300 <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="fu">overlapsAny</span>(peaks<span class="sc">$</span>msc_p300, peaks<span class="sc">$</span>heart_p300, <span class="at">type =</span> <span class="st">"any"</span>))<span class="sc">/</span><span class="fu">length</span>(peaks<span class="sc">$</span>msc_p300)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in .merge_two_Seqinfo_objects(x, y): Each of the 2 combined objects has sequence levels not in the other:
  - in 'x': chrUn_JH584304, chrUn_GL456370, chrUn_GL456389, chrM, chrUn_GL456392
  - in 'y': chrY
  Make sure to always combine/compare objects based on the same reference
  genome (use suppressWarnings() to suppress this warning).</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Proportion of overlapping peaks between p300 in mESC and heart:"</span>, ov_p300, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Proportion of overlapping peaks between p300 in mESC and heart: 0.1991544 </code></pre>
</div>
</div>
<p>From the overlapping proportions, we could see that about 27% of H3K27ac regions in mESC are also present in the heart sample, which are most likely housekeeping genes that are active in both stem cells and heart. This might also be the reason for the 20% of overlapping between the p300 regions in both samples. Only around 8% of H3K27me3 regions in mESC overlap with H3K27me3 regions in heart, indicating that repressed regions differ strongly between mESC and heart.</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>